export const TABLE_ROWS_LIMIT = 20;

export const USER_ROLE = {
  ADMINISTRADOR: "ADMINISTRADOR",
  ENCARGADO_ASEPTICOS: "ENCARGADO_ASEPTICOS",
  ETIQUETADO: "ETIQUETADO",
} as const;

export type UserRole = (typeof USER_ROLE)[keyof typeof USER_ROLE];

export const OFFCANVAS_FUNCTIONALITIES = {
  VER_LLENADORAS: "VER_LLENADORAS",
  ASIGNAR_PRODUCTOS: "ASIGNAR_PRODUCTOS",
  ASIGNAR_LIMITES: "ASIGNAR_LIMITES",
} as const;

export type OffcanvasFunctionality =
  (typeof OFFCANVAS_FUNCTIONALITIES)[keyof typeof OFFCANVAS_FUNCTIONALITIES];
